DROP DATABASE IF EXISTS `gamePJ`;
CREATE DATABASE `gamePJ`;
USE `gamePJ`;

CREATE TABLE `member`(
	id INT(100) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	regDate DATETIME NOT NULL,
	loginId CHAR(100) NOT NULL UNIQUE,
	loginPw CHAR(100) NOT NULL,
	nickName CHAR(100) NOT NULL UNIQUE,
	tire INT(100) UNSIGNED NOT NULL DEFAULT 0
);

CREATE TABLE lanking(
	id INT(100) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	regDate DATETIME NOT NULL,
	nickName CHAR(100) NOT NULL,
	tire INT(100) UNSIGNED NOT NULL
);